# -*- coding: utf-8 -*-
"""Web Scrapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lDHmt1kfPHcwitvgKgnwf-2Tb1wgtFV1
"""

!pip install trafilatura

"""# Scrapping from diffrenet Url"""

import trafilatura

array_links = [
    "https://en.wikipedia.org/wiki/Coronavirus_disease_2019", 
    "https://en.wikipedia.org/wiki/Recession", 
    "https://en.wikipedia.org/wiki/Vienna", 
    "https://en.wikipedia.org/wiki/Machine_learning", 
    "https://en.wikipedia.org/wiki/Graph_database"
]
array_text = []
for l in array_links:
    html = trafilatura.fetch_url(l)
    text = trafilatura.extract(html)
    text_clean = text.replace("\n", " ").replace("\'", "")
    array_text.append(text_clean[0:5000])
    
array_text

"""# Save in Text File 

"""

textfile = open("test_file.txt", "w")
for element in array_text:
    textfile.write(element + "\n")
textfile.close()

"""# Read Text File """

f = open("test_file.txt", "r")
print(f.read())

